API_ENDPOINT = "https://www.mtggoldfish.com"
DECK_API_ENDPOINT = f"{API_ENDPOINT}/deck"
DECK_DOWNLOAD_API_ENDPOINT = f"{API_ENDPOINT}/deck/download"

MTGGOLDFISH_DECK_PAGE_DATE_FORMAT = "%b %d, %Y"
MTGGOLDFISH_EVENT_LINE_TEXT = "Event: "
MTGGOLDFISH_DECK_DATE_TEXT = "Deck Date: "
