MTGO_STANDINGS_QUARTERFINALS_CLASS = ".quarterfinals .player"
MTGO_STANDINGS_SEMIFINALS_CLASS = ".semifinals .player"
MTGO_STANDINGS_FINALS_CLASS = ".finals .player"
PAUPER_CHALLENGE_TOURNAMENT_CLASSES = [
    MTGO_STANDINGS_QUARTERFINALS_CLASS,
    MTGO_STANDINGS_SEMIFINALS_CLASS,
    MTGO_STANDINGS_FINALS_CLASS,
]
