# This workflow will run tox on push and PR to master

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pauperformance-bot[test]
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[test]
    - name: Run tox
      run: |
        tox
